// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/blog-posts/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/blog-posts/[slug]">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/blog-posts/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/blog-posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/blog-posts">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/blog-posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/contact">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/faq">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/legal-notice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/legal-notice">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/legal-notice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/our-philosophy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/our-philosophy">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/our-philosophy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/our-product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/our-product">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/our-product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/research">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/reviews">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/science/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/science">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/science/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/shipping-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/shipping-policy">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/shipping-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/subscription">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/terms-and-conditions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/terms-and-conditions">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/terms-and-conditions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/who-we-are/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/who-we-are">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/who-we-are/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/products/[handle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/[handle]">> = Specific
  const handler = {} as typeof import("../../../../src/app/products/[handle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/products/flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/flow">> = Specific
  const handler = {} as typeof import("../../../../src/app/products/flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/prelaunch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prelaunch">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/prelaunch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/subscription/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/cancel">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/subscription/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/subscription/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/lookup">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/subscription/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/subscription/pause/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/pause">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/subscription/pause/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/subscription/resume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/resume">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/subscription/resume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/webhooks/shopify-subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/shopify-subscriptions">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/webhooks/shopify-subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pages/contact">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pages/subscription/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pages/subscription">> = Specific
  const handler = {} as typeof import("../../../../src/app/pages/subscription/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
